import type { Metadata } from "next";
import { Poppins, Caveat } from "next/font/google";
import "./globals.css";
import { GsapProvider } from "@/context/Provider";
import WhatsApp from "@/components/WhatsApp";

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const caveat = Caveat({
    variable: "--font-caveat",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: {
        default: "The Grand Kalimpong Hotel",
        template: "%s | The Grand Kalimpong Hotel",
    },
    applicationName: "The Grand Kalimpong Hotel",
    description: "Generated by create next app",
    keywords:
        "hotel, Kalimpong, accommodation, cheap stay, family-friendly, BBQ, bonfire, budget, affordable, resort, sightseeing, local cuisine",
    authors: [
        {
            name: "SteadFast Web Studio",
            url: "https://steadfastweb.studio",
        },
        {
            name: "Sanchari Mandal",
            url: "https://msanchariii.vercel.app",
        },
        {
            name: "Subhradeep Sardar",
            url: "https://subhradeepsardar.vercel.app/",
        },
        {
            name: "Kankan Mondal",
            url: "https://kankanmondal22.github.io/",
        },
        {
            name: "Subha Mistry",
        },
    ],
    publisher: "SteadFast Web Studio",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <GsapProvider>
                <body
                    className={`${poppins.variable} ${caveat.variable} font-poppins bg-white antialiased`}
                >
                    {children}
                    <WhatsApp />
                </body>
            </GsapProvider>
        </html>
    );
}
